name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: simple_live_app  # 关键：所有 run 步骤默认在子目录执行

    steps:
    - uses: actions/checkout@v4  # 克隆到根目录

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: stable
        cache: true

    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: |
        flutter clean
        set PUB_HOSTED_URL=https://pub.flutter-io.cn
        set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
        flutter pub get

    - name: Check Flutter doctor (debug)
      run: flutter doctor -v  # 检查环境（VS 等工具）

    - name: Build Windows
      run: flutter build windows --release --verbose  # 详细日志

    - name: List build files (debug)
      run: dir build\windows\runner\Release\

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          build/windows/runner/Release/**
          build/windows/**/*.exe
          build/windows/**/*.msix
        if-no-files-found: warn
